/**
 * name : common.js
 * author : Aman
 * created-date : 31-May-2020
 * Description : Common message.
 */

module.exports = {
  ASSESSMENT: 'assessment',
  OBSERVATION: 'observation',
  INSTITUTIONAL: 'institutional',
  INDIVIDUAL: 'individual',
  ENTITIES: 'entities',
  OBSERVATION_METAFORM: 'defaultObservationMetaForm',
  ASSESSMENT_META_FORM_KEY: 'assessmentMetaFormKey',
  INSTITUTIONAL_METAFORM: 'defaultInstitutionalMetaForm',
  INDIVIDUAL_METAFORM: 'defaultIndividualMetaForm',
  PUBLISHED: 'published',
  ACTIVE_STATUS: 'active',
  INACTIVE_STATUS: 'inactive',
  STARTED: 'started',
  LEAD_ASSESSOR: 'LEAD_ASSESSOR',
  MANUAL_RATING: 'manual',
  POINTS_BASED_SCORING_SYSTEM: 'pointsBasedScoring',
  AUTO_RATING: 'auto',
  SUBMISSION_STATUS_RATING_PENDING: 'ratingPending',
  SUBMISSION_STATUS_COMPLETED: 'completed',
  SUBMISSION_STATUS_STARTED: 'started',
  SUBMISSION_STATUS_NOT_STARTED: 'notstarted',
  IMAGE_FORMATS: ['png', 'jpg', 'jpeg', 'svg'],
  VIDEO_FORMATS: ['webm', 'mpg', 'mp2', 'mpeg', 'mpe', 'mpv', 'ogg', 'mp4', 'm4p', 'm4v', 'avi', 'wmv'],
  DOCUMENT_FORMATS: [
    'txt',
    'csv',
    'pdf',
    'doc',
    'docx',
    'odt',
    'ppt',
    'pptx',
    'html',
    'rtf',
    'htm',
    'xls',
    'xlsx',
    'xla',
  ],
  POLL_METAFORM: 'defaultPollCreationForm',
  POLL_QUESTION_METAFORM: 'defaultPollQuestionForm',
  EMOJI: 'emoji',
  GESTURE: 'gesture',
  TAKE_POLL: '/take-poll/',
  CREATE_OBSERVATION: '/create-observation/',
  SURVEY: 'survey',
  TAKE_SURVEY: '/take-survey/',
  EXPIRED: 'expired',
  SURVEY_SUBMISSIONS: 'surveySubmissions',
  OBSERVATION_SUBMISSIONS: 'observationSubmissions',
  SUBMISSIONS: 'submissions',
  VERSION_1: 'v1',
  VERSION_2: 'v2',
  PROJECT: 'project',
  IMPROVEMENT_PROJECT: 'improvementProject',
  SCHOOL: 'school',
  DEFAULT_PAGE_NO: 1,
  DEFAULT_PAGE_SIZE: 100,
  SUCCESS: 'success',
  ASSIGN_TO_ME: 'assignedToMe',
  CREATED_BY_ME: 'createdByMe',
  DISCOVERED_BY_ME: 'discoveredByMe',
  ALL_ROLES: 'all',
  VERSION_3: 'v3',
  DRAFT: 'draft',
  PREFIX_FOR_SOLUTION_LINK: 'samiksha',
  OFF: 'OFF',
  COURSE: 'course',
  DEFAULT_SUBMISSION_REQUIRED: 1,
  DEFAULT_SURVEY_REMOVED_DAY: 15,
  LINK: 'link',
  OBEJECT_TYPE: 'objectType',
  REVOKED: "REVOKED",
  PROGRAM: "Program",
  CREATE_SURVEY: "/create-survey/",
  CREATE_OBSERVATION: "/create-observation/",
  CREATE_PROJECT: "/create-project/",

  PRIVATE: 'private',
	WRITE_PERMISSION: 'w',
	READ_PERMISSION: 'r',
  status_failure:'failure',
  status_success:'success',
  azure: "AZURE",
  SERVER_TIME_OUT: 5000,
  SOLUTION_MODEL_NAME: 'solutions',
  TARGETED_SOLUTION_TEXT:
		'View and participate in educational programs active in your location and designed for the role you selected',
   STATE_ENTITY_TYPE: "state",
   AUTH_METHOD: {
		NATIVE: 'native',
		KEYCLOAK_PUBLIC_KEY: 'keycloak_public_key',
	},
  ADMIN:'admin',
  TENANT_ADMIN:'tenant_admin',
  ORG_ADMIN:'org_admin',
  USER_PROFILE_KEY: 'userProfile.',
  USER_PROFILE_KEY_OBS: 'observationInformation.userProfile.',
  DELETE_EVENT_ENTITY: 'user',
	DELETE_EVENT_TYPE: 'delete',
  OBJECT: 'object',
  ALL_SCOPE_VALUE:'ALL',
  ADMIN_ROLE: 'admin',
};
