name: Build and Push Docker Image

on:
  push:
    branches:
      - test-actions     # Add other branches as needed
  pull_request:
    branches:
      - test-actions
    types: [closed]

env:
  # DOCKER_IMAGE_NAME: samiksha-service  # Configure your image name here
  DOCKER_REGISTRY: docker.io
  # DOCKER_NAMESPACE: shikshalokamqa
  DOCKER_IMAGE_NAME: test-githib-workflow

jobs:
  build-and-push:
    # Only run on merged PRs or direct pushes to specified branches
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        #images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
        tags: |
          # Set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
          # Branch name tag
          type=ref,event=branch
          # PR number tag
          type=ref,event=pr
          # Semantic versioning tags (if you use version tags)
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          # SHA tag for unique identification
          type=sha,prefix={{branch}}-
          # Custom staging tag when pushed to staging branch
          type=raw,value=test-actions-{{date 'YYYYMMDD-HHmmss'}},enable={{is_default_branch}}
    
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile  # Adjust path if needed
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64  # Multi-platform support
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Image digest
      run: echo "Image pushed with digest  ${{ steps.build.outputs.digest }}"
      
    - name: Print pushed tags
      run: |
        echo "Pushed tags:"
        echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'