name: Build and Push Docker Image

on:
  push:
    branches:
      - test-actions
  workflow_dispatch:
    inputs:
      custom_tag:
        description: 'Custom tag name for the Docker image'
        required: false
        default: 'manual-build'
        type: string

env:
  DOCKER_IMAGE_NAME: test-githib-workflow
  DOCKER_REGISTRY: docker.io
  DOCKER_NAMESPACE: priyanka2171

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set custom tag
      id: tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.custom_tag }}" ]; then
          echo "tag=${{ github.event.inputs.custom_tag }}" >> $GITHUB_OUTPUT
        else
          echo "tag=test-actions-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        platforms: linux/amd64,linux/arm64
        
    - name: Print image info
      run: |
        echo "Image pushed: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}"