module.exports = {
  name: 'criteria',
  schema: {
    externalId: {
      type: String,
      index: true,
    },
    owner: String,
    timesUsed: Number,
    weightage: Number,
    name: String,
    score: String,
    remarks: String,
    showRemarks: Boolean,
    description: String,
    resourceType: [String],
    language: [String],
    keywords: [String],
    concepts: ['json'],
    createdFor: [String],
    createdFor: [String],
    rubric: Object,
    evidences: ['json'],
    flag: Object,
    criteriaType: { type: String, default: 'manual' },
    frameworkCriteriaId: 'ObjectId',
    parentCriteriaId: 'ObjectId',
    orgIds: {
      type: Array,
      require: true,
      index: true,
    },
    tenantId: {
      type: String,
      require: true,
      index: true,
    },
  },
  compoundIndex: [
    {
      name: { externalId: 1, tenantId: 1, orgIds: 1 },
      indexType: { unique: true },
    },
  ],
};
